server:
  port: 8098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eurekaservers-login.apps.us-east-1.starter.openshift-online.com/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: provider-service
  
management:
  security:
    enabled: false

logging:
  level:
    com.eureka.provider: DEBUG